import type { LucideIcon } from 'lucide-react'
import {
  Anchor,
  Apple,
  Archive,
  Award,
  Beer,
  Bike,
  Bird,
  Bone,
  BookOpen,
  Bookmark,
  Box,
  Brush,
  Bug,
  Building2,
  CalendarDays,
  Camera,
  Candy,
  Car,
  Castle,
  Cat,
  Cherry,
  Clock,
  Cloud,
  Clover,
  Coffee,
  Compass,
  Crosshair,
  Crown,
  Dice5,
  Dices,
  Dog,
  Feather,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Globe,
  Headphones,
  Heart,
  Home,
  Hourglass,
  IceCreamCone,
  Joystick,
  Landmark,
  Layers,
  Leaf,
  Library,
  ListChecks,
  ListOrdered,
  Map,
  Medal,
  Mic,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pizza,
  Plane,
  Puzzle,
  Rabbit,
  Radio,
  Rainbow,
  Rocket,
  Shield,
  ShieldCheck,
  Skull,
  Smile,
  Snowflake,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sword,
  Swords,
  Tag,
  Tags,
  Target,
  ThumbsUp,
  Timer,
  Trophy,
  Tv,
  Umbrella,
  Wand2,
  Waves,
  Wine,
  Zap
} from 'lucide-react'

/**
 * Набор иконок для пикера списка (06 §3.2: «~80 иконок набора дизайн-системы, поиск»).
 * Ключ — то же имя, что хранится в `ListDto.icon` (kebab-case, как `STATUS_META[...].icon`).
 */
export const LIST_ICONS: Record<string, LucideIcon> = {
  'gamepad-2': Gamepad2,
  heart: Heart,
  star: Star,
  'book-open': BookOpen,
  trophy: Trophy,
  flame: Flame,
  sparkles: Sparkles,
  sparkle: Sparkle,
  rocket: Rocket,
  ghost: Ghost,
  skull: Skull,
  sword: Sword,
  swords: Swords,
  shield: Shield,
  'shield-check': ShieldCheck,
  crown: Crown,
  gem: Gem,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  snowflake: Snowflake,
  leaf: Leaf,
  mountain: Mountain,
  waves: Waves,
  anchor: Anchor,
  compass: Compass,
  map: Map,
  globe: Globe,
  home: Home,
  'building-2': Building2,
  castle: Castle,
  landmark: Landmark,
  palette: Palette,
  music: Music,
  film: Film,
  camera: Camera,
  tv: Tv,
  radio: Radio,
  headphones: Headphones,
  mic: Mic,
  'pen-tool': PenTool,
  brush: Brush,
  'wand-2': Wand2,
  zap: Zap,
  target: Target,
  crosshair: Crosshair,
  'dice-5': Dice5,
  dices: Dices,
  puzzle: Puzzle,
  joystick: Joystick,
  bike: Bike,
  car: Car,
  plane: Plane,
  medal: Medal,
  award: Award,
  gift: Gift,
  'party-popper': PartyPopper,
  coffee: Coffee,
  pizza: Pizza,
  'ice-cream-cone': IceCreamCone,
  candy: Candy,
  beer: Beer,
  wine: Wine,
  cherry: Cherry,
  apple: Apple,
  fish: Fish,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  bug: Bug,
  bone: Bone,
  'paw-print': PawPrint,
  feather: Feather,
  'flower-2': Flower2,
  sprout: Sprout,
  clover: Clover,
  umbrella: Umbrella,
  rainbow: Rainbow,
  bookmark: Bookmark,
  library: Library,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  layers: Layers,
  box: Box,
  package: Package,
  archive: Archive,
  folder: Folder,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  'calendar-days': CalendarDays,
  flag: Flag,
  tag: Tag,
  tags: Tags,
  'thumbs-up': ThumbsUp,
  smile: Smile
}

export const LIST_ICON_IDS = Object.keys(LIST_ICONS)

export const DEFAULT_LIST_ICON = 'list-checks'

/**
 * 8 предустановленных цветов списка + возможность произвольного (06 §3.2).
 * Это значения пользовательских данных (`ListDto.color`), а не цвета интерфейса,
 * поэтому они заданы как литералы, а не токены (правило 04 §1 касается UI-хрома).
 */
export const LIST_COLOR_PRESETS: string[] = [
  '#8B7CFF', // accent
  '#34D6C4', // success
  '#E8B85A', // warning
  '#F0708A', // danger
  '#6FB4E8', // небесный (played)
  '#C9A7F5', // лавандовый (wishlist)
  '#8FA0C0', // сланцевый (backlog)
  '#5DCA5D' // зелёный metacritic
]
